demo/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^json_response/$',views.json_response,name='json_response'),
    url(r'^(\d+)/$',views.good_detail,name='good_detail'),
]

fruitday/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^demo/',include('demo.urls',namespace='demo')),
    url(r'^search/',include('haystack.urls')),

]

demo/models.py
from django.db import models

class GoodsType(models.Model):
    title=models.CharField('名称',max_length=20)
    desc=models.CharField('描述',max_length=200,default='商品描述',db_column='desc')
    flag=models.IntegerField(default=0)
    picture=models.ImageField(upload_to='static/',default="normal.png")
    isDelete=models.BooleanField(default=False)
    class Meta:
        db_table='goods_type'
    def __str__(self):
        return self.title


class Goods(models.Model):
    title=models.CharField('名称',max_length=20)
    price=models.DecimalField('价格',max_digits=8,decimal_places=2,default=0)
    desc=models.CharField('描述',max_length=1000,db_column='desc')
    picture=models.ImageField(upload_to='static/')
    isDelete=models.BooleanField(default=False)
    type=models.ForeignKey(GoodsType,related_name='goods')

    class Meta:
        db_table='goods'
    def __str__(self):
        return self.title

demo/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404
from .models import GoodsType,Goods
import random
from django.views.decorators.csrf import csrf_exempt
import json
from decimal import Decimal
def home(request):
    good_type=GoodsType.objects.all()
    type_list=[]
    for item in good_type:
        print(item)
        type_list.append(item)

    return render(request,'demo/home.html',{'type':type_list})

#自定义decimal类型字符的json处理
class DecimalEncoder(json.JSONEncoder):
    def _iterencode(self,o,markers=None):
        if isinstance(o,Decimal):
            return float(o)
        return super(DecimalEncoder,self)._iterencode(o,markers)





@csrf_exempt
def json_response(request):
    goods_list = []
    if request.is_ajax():
        id=request.POST['id']
        goodtype=get_object_or_404(GoodsType,pk=id)
        goods=goodtype.goods.order_by('-type__flag')[:4]
        for good in goods:
            #price = DecimalEncoder(good.price)
            #print(price)
            print(str(good.price))
            good_info={'good_id':good.id,'name':good.title,'price':str(good.price),'img':good.picture.url}
            goods_list.append(good_info)

    return HttpResponse(json.dumps(goods_list),content_type='application/json')


def good_detail(request,id=None):
    good=get_object_or_404(Goods,pk=id)
    if good :
        result={'good':good}
    return render(request,'demo/detail.html',result)

demo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            天天果园-水果网购|生鲜食品|蔬菜配送首选品牌，只为一份极致
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    {% endblock %}
</head>
<body>
    {% block section %}
        <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到优选生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>睡了个觉</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
        <div class="search_bar clearfix">
		<a href="{% url 'demo:home' %}" class="logo fl"><img src="{% static 'fruitapp/images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

    {% endblock %}
    {% block content %}

        欢迎来到天天水果店!
    {% endblock %}

</body>
<footer>
    {% block foot %}
        <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>版权所有 ©2017上海天天鲜果电子商务有限公司  保留所有权利 | 沪ICP备12042163</p>
		<p>天天果园  鲜果网购</p>
	</div>
    {% endblock %}

{% block foot_js %}

{% endblock %}
</footer>
</html>

demo/templates/demo/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/slide.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

<body>
{% block content %}

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url "demo:home" %}">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{% static good.picture|cut:'static/' %}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good.title }}</h3>
			<p>{{ good.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good.price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1" onkeyup="value=this.value.replace(/\D+/g,'')">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>16.80元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="{% static "fruitapp/images/goods/goods001.jpg" %}"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="{% static 'fruitapp/images/goods/goods002.jpg' %}"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>


	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		});

    $(".add").click(function () {
        var current=parseInt($(this).prev().val());
        current+=1;

        $(this).prev().val(current);
        var price={{ good.price }};
        $(".total em").text(
            parseFloat(price*current).toFixed(2)

        );
    });
    $(".minus").click(function () {
        var current=parseInt($(this).prev().prev().val());
        current-=1;
        if (current>=1){
            $(this).prev().prev().val(current);
            var price={{ good.price }};
            $(".total em").text(
            parseFloat(price*current).toFixed(2)

        );
        }

    });
	</script>
{% endblock %}
</body>

demo/templates/demo/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block js %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/slide.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">优选生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">优选会员</a></li>
			</ul>
		</div>
	</div>
    <div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model03" class="meet">精品肉类</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="{% static 'fruitapp/images/slide.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'fruitapp/images/slide02.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'fruitapp/images/slide03.jpg' %}" alt="幻灯片"></li>
				<li><img src="{% static 'fruitapp/images/slide04.jpg' %}" alt="幻灯片"></li>

			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="{% static 'fruitapp/images/adv01.jpg' %}"></a>
			<a href="#"><img src="{% static 'fruitapp/images/adv02.jpg' %}"></a>

		</div>
	</div>
    
    {% for foo in type %}
        <div class="list_model">
        <div class="list_title clearfix">
            <h3 class="fl" id='model0{{ foo.id }}'>{{ foo.title }}</h3>
            <div class="subtitle fl">
                <span>|</span>
                <a href=""></a>
                <a href=""></a>
                <a href=""></a>
            </div>
            <a href="" class="goods_more fr" >查看更多</a>
        </div>
        <div class="goods_con clearfix">
            <div class="goods_banner fl">
{#                cut 模板过滤器 可以移除变量中指定的字符#}
                <img src="{% static foo.picture|cut:"static/" %}" alt="">
            </div>
            <ul class="goods_list fl" id="{{ foo.id }}">
                <p style="display: none">{{ foo.id }}</p>
            </ul>
        </div>
    </div>
    {% endfor %}

{% endblock %}
{% block foot_js %}
    <script>
        {# 若要在for循环中使用ajax  ,回调函数要使用递归 #}
    $(function () {
{#        var id_list=$(".fl").find("p").text();#}
        var currentIndex=1;
{#        var len={{ type }}.length#}
        var len=6;
        function newRequest(){
            if(currentIndex>len){
                return;
            }
            $.ajax({
            url: '{% url "demo:json_response" %}',
            data:{'id':currentIndex},
            datatype:'json',
            type:'POST',
            success:function (data) {

{#                for (var j = 0; j < data.length; j++) {#}
{##}
{#                    var name = data[j].name;#}
{#                    var img = data[j].img;#}
{#                    var price = data[j].price;#}
{#                    $("#"+currentIndex).append("<li><h4><a href=''>"+name+"</a></h4><a href=''><img src='/"+img+"'><a/><div class='prize'> ￥"+price+"</div></li>");#}
{#                     src后加'/',将路径指向根目录而不是相对路径 #}
{#                }#}
                $.each(data,function (i,item) {
                    var name=item.name;
                    var img=item.img;
                    var price=item.price;
                    console.log(item);
                    var url=""+item.good_id;
                    console.log(url);
                    $("#"+currentIndex).append("<li><h4><a href=''>"+name+"</a></h4><a href="+url+"><img src='/"+img+"'><a/><div class='prize'> ￥"+price+"</div></li>")

                    }
                );
                currentIndex++;
                newRequest();
            }
            });
        }
    newRequest();
    });

    </script>
{% endblock %}

demo/templates/search/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>search</title>
</head>
<body>
    {% if query %}
    <h3>搜索结果如下</h3>
        {% for object in page.objece_list %}
            <a href="/{{ result.object.id }}">{{ result.object.gtitle }}</a><br>
            {% empty %}
            <p>啥也没找到</p>
        {% endfor %}
    {% if pate.has_previous or page.has_next %}
        <div>
        {% if page.has_previous %}
            <a href="?={{ query }}&amp;page={{ page.previous_page_number }}">
        {% endif %}&laquo;上一页{% if page.has_previous %}</a>

        {% endif %}
        {% if page.has_next %}
            <a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}下一页&raquo;
        {% if page.has_next %}
        </a>
        {% endif %}
        </div>
    {% endif %}
{% endif %}
</body>
</html>